### ISSUE TITLE
Use verbatim routes files

### ISSUE THREAD

**Issue by kevgo** [alexdavid/exprestive#1]
The feature specs are more expressive if you provide direct examples for the systems under test. 
Like this:

``` cucumber
Given a routes file defining
  """
  GET /users   Users#index
  POST /users  Users#create
  """
And the following controller 
  """
  class UsersController

    index: (req, res) ->
      res.end 'hello world'
  """
When I make a request to "/users"
Then I receive a response with code: 200 and body: "hello world"
```

The multi-line strings are provided to you as a variable, similar to tables: http://cukes.info/step-definitions.html

You can use something like https://github.com/originate/kappamaki#attributes_from_sentence to parse complex sentences into a hash. Sorry no JS version yet, but should be trivial to build. 

This makes it much easier to see the syntax of routes etc, and also to iterate it during development.

**Comment by alexdavid** [comment]
:+1: I started with something similar but it felt wrong putting code in my feature files. But I inevitably had to with the tests for `resources`.

**Comment by kevgo** [comment]
This isn't code, but the developer-facing API of your library. I.e. this is how your library appears to the end user (an express developer). It's therefore okay (and a good thing) to describe it as such, directly, in the feature specs.

**Comment by alexdavid** [comment]
Do you think the string should include the top module.exports line on the routes file since it's technically part of the API?

``` cucumber
Given a routes file defining
  """
  module.exports = ({GET}) ->
    GET '/users', to: 'users#index'
    POST '/users', to: users#create'
  """
```

**Comment by kevgo** [comment]
Yeah, I could see how that would make sense in the spirit of documenting the end-user experience. 

In particular, it depends on what you are specifying. In the spec for the whole routes file, you should definitely provide the whole file content. In a spec for some edge case (like a POST route is defined, but a PUT route is requested), I could see that it is enough to only specify the routes themselves, and not the boilerplate around them, to keep the spec concise and to the point.
