### ISSUE TITLE
res.locals.routes is not set in controller actions

### ISSUE THREAD

**Issue by charlierudolph** [alexdavid/exprestive#29]
It appears the middleware that sets res.locals.routes isn't called until after exprestive calls the controller action. Thats why the feature tests passes but this fails in production.

**Comment by alexdavid** [comment]
Thanks for catching this, I've fixed it for now but I can't think of an elegant way of testing this in the feature tests. I'll look more into ways we can refactor our reverse_routing tests to catch this in the future.
