### ISSUE TITLE
Access reverse routes from this.routes from controllers

### ISSUE THREAD

**Issue by alexdavid** [alexdavid/exprestive#44]
Point `this.routes` to the reverse routes object in controllers, even if a custom routes object is provided.

**Comment by charlierudolph** [comment]
:+1: 
Maybe that happens in BaseController's constructor?
I think `res.locals.routes` should also always be set.

**Comment by alexdavid** [comment]
Yeah, that's probably a good idea to set `res.locals.routes` in any case.

I think we can do it in base controller, but it might just be easier to inject it into the instance directly.

**Comment by charlierudolph** [comment]
Along this line do you think the ability to export routes is still needed? I've never used it.

**Comment by alexdavid** [comment]
Yeah, we can probably get rid of it. I think it was there originally to optionally export to `global.routes` to access from controllers, but `this.routes` is a cleaner approach IMO

**Comment by alexdavid** [comment]
Implemented in #54
