### ISSUE TITLE
Idea: make controllers simple functions

### ISSUE THREAD

**Issue by kevgo** [alexdavid/exprestive#66]
Right now we have imitated Rails' OO structure and require the controllers in Exprestive to be classes. I'm wondering if this is really necessary. Why can't we simplify them to:

``` coffeescript
module.exports = 

  index: (req, res) ->
      res.render 'users/index'

  new: (req, res) ->
    res.render 'users/new'

  ...
```

Making controllers classes is a misguided application of OO in my opinion. We don't really need independent objects here. There is no data and no behavior to encapsulate here. We don't need polymorphism. Unlike objects, controllers must be completely stateless and immutable. Summing this up, controllers are much more functional in nature than they are OO. They take a request as input, calculate a response (using external services), and send a response as output.

OO makes sense on the domain model level, but not for controllers or views. 

Doing this also allows us to get rid of a requirement that the class name has to match the controller name. There is no more class name. The route `foo#bar` maps to the controller function keyed as `bar` in the file `foo_controller.coffee`.

@alexdavid @charlierudolph

**Comment by charlierudolph** [comment]
Sounds good to me. Based on your comments in #64, might need to be flexible with the file names though.

```
foo_controller.coffee
foo-controller.coffee
FooController.coffee
```

each is the `foo` controller

Basically take the filename, camelCase it, and remove `Controller`.

**Comment by alexdavid** [comment]
When I was first designing exprestive I debated whether to use classes or just export an object. I chose classes for a few reasons, and still think that was the right decision.

Here are a few reasons I think classes make sense
- **Dependency injection** - In every project I've used exprestive, I've found the dependencies feature incredibly useful. Basically you can specify dependencies from the server that are available in the constructor of every controller. This is useful if your app has services that are initialized in the server but need to be accessed by your controllers.
- **Loss of name attribute** - Named functions in javascript (like coffeescript/livescript classes) automatically get a `name` attribute which we use to reference from the routes file. Using file names to resolve this, as you suggest seems brittle, and introduces a lot more edge cases. This name is also used automatically in error reporting when a controller method raises an error. Finally, it permanently prevents node apps using exprestive from being compiled down to a single file, while this is not something _we_ do, it is a practice I've seen app developers do and our architecture should be flexible enough to not care how you structure your app.
- **Extend a base controller** - Extending common functionality in controllers comes free in coffeescript/livescript. This is useful functionality if you have a lot of CRUD routes. Using a base class you could do some magic to automatically wire up the RESTful verbs (index, show, etc...). Exprestive also provides an optional base controller that offers some helper methods.
- **Classes have less magic** - We could implement a lot of the issues I've documented here by using methods, but it would require significant more magic. Javascript developers are familiar with classes, they know how to create private helper methods, extend base classes, and how to call these methods from their controller methods. If I didn't know how to use exprestive and I came across an app that was using it and I saw your syntax, I would not intuitively know if I could just create private helper methods and reference them with `this` from my controller methods.
- **What are we actually saving by changing this** - In coffeescript/livescript you're saving 4 characters: `class`. For simple apps an object of methods is a good fit, but using a class isn't any more difficult, but provides much more flexibility. I'm ok with breaking changes, but only if there is a real advantage for doing so. I'd rather not have major breaking changes for the sake of having breaking changes.

**Comment by charlierudolph** [comment]
Forgot about dependencies and extending the base controller. Those are far easier with classes then introducing some new syntax.

**Comment by kevgo** [comment]
Okay, sounds good. Thanks!
